import turtle

s = turtle.screensize(700,1000)
turtle.speed(5)
def my_goto(x, y):
    turtle.penup()
    turtle.goto(x, y)
    turtle.pendown()
#time.sleep(10)
#ht()
turtle.pensize(2)
def short():
    turtle.fillcolor('#ffec40')
    turtle.begin_fill()
    turtle.right(25)
    turtle.forward(20)
    turtle.right(45)
    turtle.forward(20)
    turtle.left(70)
    turtle.forward(90)
    turtle.left(95)
    turtle.forward(75)
    turtle.left(85)
    turtle.forward(175)
    turtle.left(85)
    turtle.forward(75)
    turtle.left(95)
    turtle.forward(90)
    turtle.left(85)
    turtle.forward(18)
    turtle.end_fill()

def lleg():
    my_goto(-39,-25)
    turtle.fillcolor("#ffd699")
    turtle.begin_fill()
    turtle.right(89)
    turtle.forward(25)
    turtle.right(90)
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(20)
    turtle.right(85)
    turtle.forward(50)
    turtle.end_fill()

def lsock():
    my_goto(-36,-78)
    turtle.fillcolor("#ffffff")
    turtle.begin_fill()
    turtle.right(90)
    turtle.circle(80,13)
    turtle.right(110)
    turtle.forward(22)
    turtle.right(85)
    turtle.forward(19)
    turtle.right(90)
    turtle.forward(21)
    turtle.end_fill()

def lshoe():
    my_goto(-69,-112)
    turtle.fillcolor("#b5ae60")
    turtle.begin_fill()
    turtle.right(90)
    turtle.left(5)
    turtle.forward(56)
    turtle.left(105)
    turtle.forward(13)
    turtle.left(75)
    turtle.forward(20)
    turtle.right(90)
    turtle.forward(15)
    turtle.circle(10,15)
    turtle.left(80)
    turtle.forward(4)
    turtle.circle(10,15)
    turtle. left(40)
    turtle.circle(20,15)
    turtle.forward(10)
    turtle.right(45)
    turtle.forward(15)
    turtle.circle(25,25)
    turtle.end_fill()

def rleg():
    my_goto(60,-28)
    turtle.fillcolor("#ffd699")
    turtle.begin_fill()
    #right(90)
    turtle.left(128)
    turtle.forward(25)
    turtle.right(95)
    turtle.forward(55)
    turtle.right(90)
    turtle.forward(20)
    turtle.right(85)
    turtle.forward(55)
    turtle.end_fill()

def rsock():
    my_goto(64,-79)
    turtle.fillcolor("#ffffff")
    turtle.begin_fill()
    turtle.right(90)
    turtle.circle(90,14)
    turtle.right(110)
    turtle.forward(23)
    turtle.right(90)
    turtle.forward(15)
    turtle.right(80)
    turtle.forward(21)
    turtle.end_fill()

def rshoe():
    my_goto(64,-108)
    turtle.fillcolor("#b5ae60")
    turtle.begin_fill()
    turtle.right(100)
    turtle.forward(56)
    turtle.left(160)
    turtle.forward(25)
    turtle.right(68)
    turtle.forward(17)
    turtle.left(90)
    turtle.circle(18,15)
    turtle.forward(5)
    turtle.left(75)
    turtle.forward(11)
    turtle.right(85)
    turtle.forward(20)
    turtle.left(45)
    turtle.circle(10,30)
    turtle.left(25)
    turtle.forward(5)
    turtle.end_fill()

def shirt():
    my_goto(-75,48)
    turtle.fillcolor("red")
    turtle.begin_fill()
    turtle.left(72)
    turtle.forward(185)
    turtle.left(87)
    turtle.forward(75)
    turtle.right(68)
    turtle.circle(20,8)
    turtle.circle(300,23)
    turtle.left(90)
    turtle.circle(35,17)
    turtle.right(38)
    turtle.circle(35,17)
    turtle.left(58)
    turtle.forward(75)
    turtle.right(12)
    turtle.forward(140)
    turtle.right(40)
    turtle.forward(93)
    turtle.left(120)
    turtle.circle(-20,65)
    turtle.left(75)
    turtle.forward(10)
    turtle.left(23)
    turtle.forward(88)
    #circle(-80,10)
    turtle.right(31)
    turtle.forward(87)
    turtle.right(180)
    turtle.forward(108)
    turtle.right(180)
    turtle.forward(104)
    turtle.circle(10,70)
    turtle.end_fill()

def head():
    my_goto(-20,295)
    turtle.left(20)
    turtle.pensize(2)
    turtle.fillcolor('#fcc6a0')
    turtle.begin_fill()
    turtle.right(90)
    turtle.forward(40)
    turtle.right(90)
    turtle.circle(50,80)
    turtle.left(10)
    turtle.circle(50,80)
    turtle.left(2)
    turtle.circle(200,50)

    turtle.left(48)
    turtle.forward(60)
    #left(20)
    turtle.circle(45,60)
    turtle.right(5)
    turtle.circle(100,85)
    turtle.end_fill()
    turtle.fillcolor('black')
    turtle.begin_fill()

    turtle.pensize(2)
    turtle.right(170)
    turtle.circle(-100,165)
    turtle.right(78)
    turtle.forward(26)
    turtle.right(87)
    turtle.forward(55)
    turtle.circle(45,60)
    turtle.right(5)
    turtle.circle(100,85)
    turtle.end_fill()

    turtle.fillcolor('#fcc6a0')
    turtle.begin_fill()
    turtle.right(180)
    turtle.circle(-100,105)
    turtle.right(37)
    turtle.forward(49)
    turtle.pensize(2)
    turtle.left(130)
    turtle.forward(30)
    #right(5)
    turtle.circle(-10,70)
    turtle.right(50)
    #circle(10,10)
    turtle.forward(36)
    turtle.right(80)
    turtle.forward(50)
    turtle.pencolor('#fcc6a0')
    turtle.right(90)
    turtle.forward(30)
    
    turtle.end_fill()

def rhand():
    #left(35)
    my_goto(197,209)
    turtle.pencolor('black')
    turtle.fillcolor('#fcc6a0')
    turtle.begin_fill()
    turtle.right(45)
    turtle.forward(6)
    turtle.left(55)
    turtle.forward(20)
    turtle.circle(-5,70)
    turtle.right(100)
    turtle.forward(18)
    turtle.left(105)
    turtle.forward(18)
    turtle.circle(-5,70)
    turtle.right(100)
    turtle.forward(18)
    turtle.left(145)
    turtle.forward(15)
    turtle.circle(-5,70)
    turtle.right(100)
    turtle.forward(18)

    turtle.left(150)
    turtle.forward(13)
    turtle.circle(-5,70)
    turtle.right(100)
    turtle.forward(15)

    turtle.left(150)
    turtle.forward(10)
    turtle.circle(-5,70)
    turtle.right(100)
    turtle.forward(12)
    turtle.circle(60,10)
    turtle.left(45)
    turtle.forward(6)
    turtle.right(90)
    turtle.forward(10)
    turtle.end_fill()

def lhand():
    my_goto(-94,242)
    turtle.fillcolor('#fcc6a0')
    turtle.begin_fill()
    turtle.right(10)
    turtle.forward(6)
    turtle.left(90)
    turtle.penup()
    turtle.forward(12)
    turtle.pendown()
    turtle.left(90)
    turtle.forward(8)
    turtle.left(90)
    turtle.forward(12)
    turtle.end_fill()

def chocochips():
    my_goto(-103,291)
    turtle.right(90)
    turtle.fillcolor('#02d302')
    turtle.begin_fill()
    turtle.right(90)
    turtle.forward(55)
    turtle.left(80)
    turtle.forward(12)
    turtle.left(10)
    turtle.forward(17)
    turtle.left(10)
    turtle.forward(12)
    turtle.left(80)
    turtle.forward(55)
    turtle.left(80)
    turtle.forward(12)
    turtle.left(10)
    turtle.forward(17)
    turtle.left(10)
    turtle.forward(12)
    turtle.left(80)
    turtle.left(80)
    turtle.forward(12)
    turtle.left(10)
    turtle.forward(17)
    turtle.left(10)
    turtle.forward(12)
    turtle.end_fill()
    turtle.penup()
    turtle.right(100)
    turtle.forward(20)
    turtle.right(90)
    turtle.forward(14)
    turtle.pendown()
    turtle.pencolor('#9c5e4a')
    turtle.fillcolor('#9c5e4a')
    turtle.begin_fill()
    for i in range(5):
        turtle.forward(15)
        turtle.right(144)
    turtle.end_fill()
    turtle.penup()
    turtle.forward(27)
    turtle.left(90)
    turtle.forward(16)
    turtle.left(90)
    turtle.forward(7)
    turtle.pendown()
    turtle.fillcolor('#9c5e4a')
    turtle.begin_fill()
    for i in range(5):
        turtle.forward(10)
        turtle.right(144)
    turtle.end_fill()
    turtle.penup()
    turtle.forward(20)
    turtle.right(90)
    turtle.forward(5)
    turtle.pendown()
    turtle.fillcolor('#9c5e4a')
    turtle.begin_fill()
    for i in range(5):
        turtle.forward(10)
        turtle.right(144)
    turtle.end_fill()
    turtle.penup()
    turtle.right(180)
    turtle.forward(6)
    turtle.pendown()
    turtle.fillcolor('#9c5e4a')
    turtle.begin_fill()
    for i in range(5):
        turtle.forward(10)
        turtle.right(144)
    turtle.end_fill()

def lhand2():
    my_goto(-112,284)
    turtle.pencolor('black')
    turtle.fillcolor('#fcc6a0')
    turtle.begin_fill()
    turtle.right(180)
    turtle.forward(31)
    turtle.left(90)
    for i in range(2): 
        turtle.circle(4,90) 
        #circle(4//2,45)
    for i in range(3):
        turtle.right(180)
        for i in range(2): 
            turtle.circle(4,90)
    turtle.end_fill()

def mouth():
    my_goto(-25,200)
    turtle.left(65)
    turtle.fillcolor('#77332e')
    turtle.begin_fill()
    #circle(20)
    #forward(20)
    for i in range(2): 
        turtle.circle(25,90) 
        turtle.circle(25//2,90)
    turtle.end_fill()

def eyebrow(x,y):
    my_goto(x,y)
    turtle.pensize(18)
    turtle.right(150)
    turtle.forward(25)
    turtle.right(90)
    for i in range(1):
        turtle.right(45)
        turtle.dot(15)
    turtle.left(55)
    turtle.forward(25)
    for i in range(1):
        turtle.right(45)
        turtle.dot(15)

def eyelid(x,y):
    my_goto(x,y)
    turtle.pensize(2)
    turtle.left(170)
    turtle.circle(-23,180)

def eyes1(x,y):
    my_goto(x,y)
    turtle.right(90)
    turtle.fillcolor('#000000')
    turtle.begin_fill()
    turtle.circle(18)
    turtle.end_fill()
    turtle.left(90)
    turtle.penup()
    turtle.forward(19)
    turtle.right(90)
    turtle.forward(7)
    turtle.pendown()
    turtle.fillcolor('#ffffff')
    turtle.begin_fill()
    turtle.left(90)
    turtle.circle(9)
    turtle.end_fill()

def eyes2(x,y):
    my_goto(x,y)
    turtle.right(90)
    turtle.fillcolor('#000000')
    turtle.begin_fill()
    turtle.circle(18)
    turtle.end_fill()
    turtle.left(90)
    turtle.penup()
    turtle.forward(19)
    turtle.right(90)
    turtle.forward(8)
    turtle.pendown()
    turtle.fillcolor('#ffffff')
    turtle.begin_fill()
    turtle.left(90)
    turtle.circle(9)
    turtle.end_fill()

def robo():
    my_goto(155,-105)
    turtle.left(93)
    turtle.color('red')
    turtle.pensize(7)

    turtle.begin_fill()
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.end_fill()


    turtle.color('white')
    turtle.penup()
    turtle.left(90)
    turtle.forward(30)
    turtle.right(90)
    turtle.forward(12)
    turtle.pendown()
    turtle.pensize(3)
    turtle.circle(5)
    turtle.penup()
    turtle.forward(25)
    turtle.pendown()
    turtle.circle(5)

    turtle.penup()
    turtle.right(90)
    turtle.forward(20)
    turtle.right(90)
    turtle.pendown()

    turtle.begin_fill()
    turtle.forward(23)
    turtle.right(90)
    turtle.forward(7)
    turtle.right(90)
    turtle.forward(23)
    turtle.right(90)
    turtle.forward(7)
    turtle.right(90)
    turtle.end_fill()

    turtle.penup()
    turtle.forward(25)
    turtle.right(90)
    turtle.forward(35)
    turtle.pendown()

    turtle.color('red')
    turtle.forward(30)
    turtle.penup()
    turtle.right(90)
    turtle.pendown()
    turtle.begin_fill()
    turtle.circle(5)
    turtle.end_fill()

def legs():
    lleg()
    lsock()
    lshoe()
    rleg()
    rsock()
    rshoe()

def hands():
    rhand()
    lhand()
    chocochips()
    lhand2()

def eyebrows():
    eyebrow(-8,300)
    turtle.right(90)
    eyebrow(72,300)
    eyelid(-9,270)
    turtle.left(15)
    eyelid(68,265)    

def eyes():
    eyes1(17,275)
    eyes2(95,270)
